name: ap-ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
  schedule:
    - cron: '0 0 * * 0'

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      # Check out the code from the repository.
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - name: Setup node env with node version ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      # Install the dependencies.
      - name: Install Node Dependencies
        run: cd backend && npm ci

      # Run the tests.
      - name: Execute Tests
        run: cd backend && npm test 

      # Run the linter.
      - name: Run the linter
        run: cd backend && npm run lint
        continue-on-error: true

      # Send a console message at completion.
      - name: Print message
        run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
